Fix build on macos
Seems we can't call our fwrite()/fwrite_unlocked() wrapper FWRITE() because
then macos errors out on uses with:

    error: called object type 'int' is not a function or function pointer

It's unclear what's going on - a conditional `#undef FWRITE` before
defining doesn't help.

Thanks Apple!